# <center>NumPy</center>


## What is NumPy?

- NumPy is the fundamental package for scientific computing in Python.
- NumPy is a Python library that provides a multidimensional array object, various derived objects


<hr>

## What Is NumPy Array?

- An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.
  - 0D Array - Scalar
  - 1D Array - like a list, “vector”
  - 2D Array - like a table, “matrix”
  - 3D Array or more - set of tables, perhaps stacked, “tensor”
  - Higher-Dimensional Array


<pre>NOTE: </pre>
The dimension of an array is sometimes referred to as an “axis”. This terminology may be useful to disambiguate between the dimensionality of an array and the dimensionality of the data represented by the array.

Most NumPy arrays have some restrictions. <br>
For instance:

- All elements of the array must be of the same type of data.

- Once created, the total size of the the array can’t change.

- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.


<hr>

## NumPy vs Python List

- Advantages of using Numpy Arrays Over Python Lists:
  - consumes less memory.
  - fast as compared to the python List.
  - convenient to use.

<details open> 
<summary>Why is NumPy fast?</summary>
Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking placein optimized, pre-compiled C code.

Vectorized code has many advantages, among which are:

- vectorized code is more concise and easier to read

- fewer lines of code generally means fewer bugs

- the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)

- vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

</details>


In [128]:
import numpy as np

import time

In [3]:
pythonList = [1, 2, 3, 4]
print(pythonList)

print(type(pythonList))

[1, 2, 3, 4]
<class 'list'>


In [9]:
npArray = np.array([1, 2, 3, 4])
print(npArray)

print(type(npArray))

[1 2 3 4]
<class 'numpy.ndarray'>


In [160]:
%timeit [i**10 for i in range(1, 11)]

1.27 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [161]:
%timeit np.arange(1, 11)**10

2.87 µs ± 544 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [186]:
# Python list example
pythonSampleList = [1, 2, 3, 4, 5]

start_time = time.time()

totalSum = 1
for i in range(len(pythonSampleList)):
    for j in range(len(pythonSampleList)):
        totalSum *= (pythonSampleList[i]**2) * (pythonSampleList[j]**2)

end_time = time.time()

duration = end_time - start_time
print('Python List Duration: {:.6f} seconds'.format(duration))
print('Python List TotalSum:', totalSum)

# Numpy array example
npSampleArray = np.array([1, 2, 3, 4, 5], dtype=np.float64)

start_time = time.time()

totalSum = 1.0
for i in range(len(npSampleArray)):
    for j in range(len(npSampleArray)):
        totalSum *= (npSampleArray[i]**2) * (npSampleArray[j]**2)

end_time = time.time()

duration = end_time - start_time
print('Numpy Array Duration: {:.6f} seconds'.format(duration))
print('Numpy Array TotalSum:', totalSum)

Python List Duration: 0.001000 seconds
Python List TotalSum: 383375999244747512217600000000000000000000
Numpy Array Duration: 0.001005 seconds
Numpy Array TotalSum: 3.8337599924474756e+41


<hr>

## Difference Between NumPy Array and List in Python

- Data types storage
- Importing module
- Numerical operation
- Modification capabilities
- Consumes less memory
- Fast as compared to the python list
- Convenient to use


One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [187]:
# Python list example
python_list = [1, 2, 3, 4, 5]
sliced_list = python_list[1:4]
sliced_list[0] = 99

print("Original list:", python_list)
print("Sliced list:", sliced_list)




# NumPy array example
np_array = np.array([1, 2, 3, 4, 5])
sliced_array = np_array[1:4]
sliced_array[0] = 99

print("Original array:", np_array)
print("Sliced array:", sliced_array)

Original list: [1, 2, 3, 4, 5]
Sliced list: [99, 3, 4]
Original array: [ 1 99  3  4  5]
Sliced array: [99  3  4]


<pre>NOTE: </pre>This behavior of NumPy arrays is particularly useful for working with large datasets, as it avoids unnecessary copying and saves memory and computational resources.

Another difference between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square brackets, separated by commas. For instance, the element 8 is in row 1 and column 3:

In [188]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[1, 3]

8

<hr>

## Importance of NumPy in Python

- wide variety of mathematical operations on arrays.
- It supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.
- Mathematical, logical, shape manipulation, sorting, selecting, I/O, Discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


## Creating NumPy Arrays

- To create a NumPy array, you can use the function np.array().


In [29]:
tempList = [10, 20, 30]
npArray = np.array(tempList)
print(npArray)

print(tempList, '  =>  ', type(tempList))
print(npArray, '  =>  ', type(npArray))

[10 20 30]
[10, 20, 30]   =>   <class 'list'>
[10 20 30]   =>   <class 'numpy.ndarray'>


<hr>

## How to create a basic array

- Create an array filled with 0’s:

In [189]:
np.zeros(2)

array([0., 0.])

<br><br>

- An array filled with 1’s:

In [190]:
np.ones(2)

array([1., 1.])

<br><br>

- An empty array! 

    The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [204]:
np.empty(2)

array([1., 1.])

<br><br>

- An array with a range of elements

In [205]:
np.arange(4)

array([0, 1, 2, 3])

<br><br>

- A range of evenly spaced intervals

In [206]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [211]:
np.arange(0, 2, 0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

<pre>NOTE:</pre>
When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. <br>
For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step.

<br><br>

- Create an array with values that are spaced linearly in a specified interval

In [210]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

<br><br>
Specifying your data type

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [214]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

## Array attributes

In [216]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

<br>

ndim

- The number of dimensions of an array is contained in the ndim attribute.

In [221]:
print("The Dimension is:", x.ndim)

The Dimension is: 2


<br>

shape

- The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [224]:
print("The Shape is:", x.shape)

The Shape is: (3, 4)


In [222]:
len(x.shape) == x.ndim

True

<br>

size

- The fixed, total number of elements in array is contained in the size attribute.

In [225]:
print("Total elements are:", x.size)

Total elements are: 12


<br>

dtype

- The data type is recorded in the dtype attribute.

    Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”.

In [226]:
print("The Data Type is:", x.dtype)

The Data Type is: int32
