# <center>NumPy</center>


### What is NumPy?

- NumPy is the fundamental package for scientific computing in Python.
- NumPy is a Python library that provides a multidimensional array object, various derived objects


### What Is NumPy Array?

- An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.
  - 1D Array
  - 2D Array
  - 3D Array
  - Higher-Dimensional Array


### NumPy vs Python List

- Advantages of using Numpy Arrays Over Python Lists:
  - consumes less memory.
  - fast as compared to the python List.
  - convenient to use.


In [1]:
import numpy as np

In [2]:
npArray = np.array([1, 2, 3, 4])
print(npArray)

print(type(npArray))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
pythonList = [1, 2, 3, 4]
print(pythonList)

print(type(pythonList))

[1, 2, 3, 4]
<class 'list'>


### Difference Between NumPy Array and List in Python

- Data types storage
- Importing module
- Numerical operation
- Modification capabilities
- Consumes less memory
- Fast as compared to the python list
- Convenient to use


In [19]:
%timeit [i**10 for i in range(1, 11)]

968 ns ± 18 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
%timeit np.arange(1, 11)**10

2.07 µs ± 29.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Importance of NumPy in Python

- wide variety of mathematical operations on arrays.
- It supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.
- Mathematical, logical, shape manipulation, sorting, selecting, I/O, Discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


### Creating NumPy Arrays

- To create a NumPy array, you can use the function np.array().


In [29]:
tempList = [10, 20, 30]
npArray = np.array(tempList)
print(npArray)

print(tempList, '  =>  ', type(tempList))
print(npArray, '  =>  ', type(npArray))

[10 20 30]
[10, 20, 30]   =>   <class 'list'>
[10 20 30]   =>   <class 'numpy.ndarray'>


###

-


###

-
